kind: Template
apiVersion: v1
metadata:
  name: deploy-mserv-java-springboot
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
<<<<<<< HEAD
    creationTimestamp: '2019-12-10T19:01:00Z'
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
=======
    creationTimonthtamp: '2019-12-10T19:01:00Z'
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namonthpace: ${APP_NAmonthPACE}
>>>>>>> fc7735d5ffaacc64864999711204d558c13ca139
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'httpd:2.4'
<<<<<<< HEAD
          namespace: openshift
=======
          namonthpace: openshift
>>>>>>> fc7735d5ffaacc64864999711204d558c13ca139
      type: Source
    triggers: []
  status: {}

- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
  status: {}
parameters:
- name: APP_NAME
  required: true
  value: "datos-abiertos-frontend"
<<<<<<< HEAD
- name: APP_NAMESPACE
=======
- name: APP_NAmonthPACE
>>>>>>> fc7735d5ffaacc64864999711204d558c13ca139
  required: true
